//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJMRP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbintjmrpEntities : DbContext
    {
        public dbintjmrpEntities()
            : base("name=dbintjmrpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArchive> tblArchives { get; set; }
        public virtual DbSet<tblCurrentIssue> tblCurrentIssues { get; set; }
        public virtual DbSet<tblGroup> tblGroups { get; set; }
        public virtual DbSet<tblIndexImage> tblIndexImages { get; set; }
        public virtual DbSet<tblNew> tblNews { get; set; }
        public virtual DbSet<tblWebtext> tblWebtexts { get; set; }
        public virtual DbSet<tblUserLogin> tblUserLogins { get; set; }
    }
}
