//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJMRP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArchive
    {
        public string ARCHIVE_DETAILS { get; set; }
        public Nullable<System.DateTime> ARCHIVE_YEAR { get; set; }
        public string ARCHIVE_FILE { get; set; }
    }
}
