//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJMRP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrentIssue
    {
        public int CURENTISSUE_ID { get; set; }
        public string CURENTISSUE_GROUP { get; set; }
        public string CURENTISSUE_NAME { get; set; }
        public string CURENTISSUE_AUTHOR { get; set; }
        public string CURENTISSUE_ABSTRACT { get; set; }
        public string CURENTISSUE_ARCHIVE_ID { get; set; }
        public string CURENTISSUE_FILEPATH { get; set; }
        public Nullable<System.DateTime> CURENTISSUE_DATE { get; set; }
    }
}
