//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJMRP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLogin
    {
        public string U_USERID { get; set; }
        public string U_USERNAME { get; set; }
        public string U_MOBILE { get; set; }
        public string U_EMAIL { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_ROLE { get; set; }
    }
}
