//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJMRP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebtext
    {
        public string WEB_ID { get; set; }
        public string WEB_NAME { get; set; }
        public Nullable<System.DateTime> WEB_DATE { get; set; }
        public string WEB_DESC { get; set; }
    }
}
